version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    working_dir: /usr/src/backend
    volumes:
      - './backend:/usr/src/backend'
    ports:
      - '7878:7878'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.5.8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
